### PR TITLE
SSL Implementation

### LINKED ISSUE #8: Use secure connection for Ipe server
Hi, not sure if it's an issue but.. is it possible to use a secure connection for the Ipe server? If so, how can I configure it? I couldn't find it anywhere.

### PR DESCRIPTION
**Pull request by welingtonsampaio**
This is an early stage implementation in order to resolve #8. It implements support of secure connections between clients and ipe server. The folowing keys were added in server configuration in order to setup a secure server:

```json
{
	"Encrypted": true,
	"SSLPrivateKey": "/home/ssl.key",
	"SSLPublicKey": "/home/ssl.crt"
}
```

As in Pusher, the clients must be configured to use secure connection too by providing the options `encrypted` and `wssPort`

### CODE REVIEW

**Comment by dimiro1** [comment]
I think the best way is to run two webservers one with SSL and another without SSL running on differente ports. This way we can force SSL only on certain Apps (This is already implemented here https://github.com/dimiro1/ipe/blob/master/ipe/websockets.go#L47) what do you think?

**Comment by welingtonsampaio** [comment]
I think it's a valid idea as it is faster to process, however I didn't understand the flow you mentioned, could you elaborate a bit more on what could be implemented in order to achieve that?  The configuration part for running on different ports two instances is already being done.

**Comment by dimiro1** [comment]
Something like this.

```
go func() {
        log.Fatal(http.ListenAndServe(conf.Host, router))
}
log.Fatal(http.ListenAndServeTLS(conf.SSLHost, conf.SSLPublicKey, conf.SSLPrivateKey, router))
```

Each app have a flag OnlySSL[1], if it is true then when the pusher client try to connect without SSL the Websocket server reply with an error message[2][3] saying that the client must reconnect but with SSL enabled. The js client handle this and reconnect.

I think we need to emulate the correct behavior of the Pusher server including handling SSL correctly.

See [4][5]

[1] https://github.com/dimiro1/ipe/blob/master/ipe/app.go#L24
[2] https://github.com/dimiro1/ipe/blob/master/ipe/websockets.go#L47
[3] https://github.com/dimiro1/ipe/blob/master/ipe/errors.go#L78
[4] https://pusher.com/docs/client_api_guide/client_connect
[5] https://pusher.com/docs/pusher_protocol

**Comment by welingtonsampaio** [comment]
Gotcha. I think it would be more interesting to put all available options inside the config file so we can find them easily. Also, we could start a wiki to bootstrap the documentation. What do you think?

**Comment by dimiro1** [comment]
I do not like wikis :). I think we can add a Bootstrap section in the README file. Also the project have a simple functional test suite [1] that I run by hand to test the integration with the Pusher JS lib. I would be very happy if you add some tests to validate this SSL stuff.

[1] https://github.com/dimiro1/ipe/tree/master/functional

**Comment by dimiro1** [comment]
@welingtonsampaio I merged your PR and I made some changes on the master branch. Thank you very much for your time.

**Pull request merged**
